### ISSUE TITLE
invincble enemies

### ISSUE THREAD

**Issue by DannyDarth** [tiltedphoques/TiltedEvolution#250] opened 2022-07-10 22:15 UTC
occasionally enemies dont seem to take damage or die.

**Comment by Pingu-Pox** [comment] 2022-07-10 23:11
This is addressed in their wiki, try this mod in your loadorder.
No Killmoves - No Killcams - No Killbites SE
https://www.nexusmods.com/skyrimspecialedition/mods/13395

**Comment by RobbeBryssinck** [comment] 2022-07-11 06:42
Duplicate of #211

**Closed by RobbeBryssinck** 2022-07-11 06:42 UTC
