### ISSUE TITLE
Consuming ingredients show effects on every player

### ISSUE THREAD

**Issue by theo-ardouin** [tiltedphoques/TiltedEvolution#380] opened 2022-07-23 12:26 UTC
## Description

When consuming an ingredient, it shows the effect (green blur) on all players.

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Connect on a server
2. Eat an ingredient on the same cell as another player
3. The other player will have a colored-blurry screen due to the effect of someone else eating an ingredient

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

The ingredient-eating player is the only one with the effect on his screen

## Evidence (optional)

Show us what happened.

**Comment by Astral3** [comment] 2022-08-15 01:22
@Dragonisser This is a duplicate of #363 and is also mentioned in #387 and so can be closed.

**Closed** 2022-08-16 15:48 UTC
Labels: bug
