### ISSUE TITLE
Dying in tutorial dungeon might get u stuck

### ISSUE THREAD

**Issue by French-Asgeir** [tiltedphoques/TiltedEvolution#360] opened 2022-07-17 23:48 UTC
## Description

Dying after the underground bridge from helgen get you to respawn before the collapsed bridge were rock now block the entrance.

Related formIDs|
---------------|
None

## Steps to reproduce

1. Start a new game.
2. Clear the tutorial until you encounter the spiders.
3. Die to the spider.
4. You now have respawned before the collapsed bridge with new found rock blocking further progression.
5. Only option is to reload before this point.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Either removing the rock entirely or creating a custom spawn point for the tutorial after the bridge.

## Evidence
![Capture4](https://user-images.githubusercontent.com/109287366/179429895-daae00db-de06-4dd5-9d85-7439d7437121.PNG)

**Comment by MatthewTeply** [comment] 2022-07-18 12:02
Not sure if this is really relevant, you should really use the Skyrim Together client only when you really are planning on playing coop.

**Comment by French-Asgeir** [comment] 2022-07-18 12:20
> Not sure if this is really relevant, you should really use the Skyrim Together client only when you really are planning on playing coop.

The guide only mention that you shouldn't connect during tutorial. I doesn't forbid you to use the client.

**Comment by Thercious** [comment] 2022-07-18 13:28
I think it's implicited. But ideally, you should either use a mod like [Alternate Start - Live Another Life - SSE](https://www.nexusmods.com/skyrimspecialedition/mods/272) (which allows you to start in one of the main cities and play with your friends in just a couple of minutes), or use the mod with a character that's already past the tutorial.

**Comment by French-Asgeir** [comment] 2022-07-18 15:44
I wouldn't consider using an external mod or using a console command a proper fix, it's not helping beginner user even if it appear simple from our pov. 

We should either update the guide to recommand starting the game from an unmodded character and using the client once outside of helgen as @Thercious and @MatthewTeply said or apply what I proposed or find another method we didn't think of yet.

**Comment by EnoughReality** [comment] 2022-07-20 17:20
from the main menu just press the tilde key and use "coc riverwood"

**Comment by BennyOfEarth** [comment] 2022-07-20 22:36
> > Not sure if this is really relevant, you should really use the Skyrim Together client only when you really are planning on playing coop.
> 
> The guide only mention that you shouldn't connect during tutorial. I doesn't forbid you to use the client.

The coding in the tutorial is apparently done weirdly, so it doesn't interact properly, hence they specifically say not to. They are aware that there are issues there, but I don't think it's really worth the effort for them to make it work properly, just play through Helgen solo and join up after.

**Comment by JacobLouis** [comment] 2022-08-02 20:28
When you die without the mod it reloads the last save. This can easily be resolved by manually reloading the last save. I would argue this is working as designed and not a bug.

**Closed** 2022-08-26 15:06 UTC
Labels: bug
