### ISSUE TITLE
Forbidden Legend Claw Puzzle Crashes Game

### ISSUE THREAD

**Issue by AGalacticFish** [tiltedphoques/TiltedEvolution#568] opened 2023-02-01 09:36 UTC
# READ IF YOU HAVE MODS

Tested without mods and with only STR, STR is the issue.

1.3.2 Version of Skyrim Together

-->

*For example:*

v1.1.0

## Description

A clear and concise description of what the bug is, Include any formIDs relevant for us to use E.g.,

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

1. Walk to Reachwater Rock. 
2. Enter Reachwater Rock.
3. Pick up claw from pedestal.
4. Enter the correct combination for the puzzle.
5. Quick save to reproduce bug quickly.
6. Insert claw into door.
7. Door moves slightly before crash to desktop. 

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [X ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

Claw puzzle door to open so I can proceed with the quest.

Describe your expected result i.e. answer the question "What did you expect would happen?"

## Evidence (optional)

Show us what happened.

**Comment by stenliis** [comment] 2023-02-01 20:37
duplicate of #561

**Closed** 2023-07-21 16:37 UTC
Labels: bug
