### ISSUE TITLE
Sleeping in groups will only work when all group members are going to sleep

### ISSUE THREAD

**Issue by Hexenhub** [tiltedphoques/TiltedEvolution#526] opened 2022-10-12 10:04 UTC
### **Description**
When a group member likes to go to sleep, all other group members needs to sleep, too (like it is in minecraft for example).
Therefor the group leader would set the duration of sleeping in his UI and this duration would be synchronised with all the other group members so they would only need to press "E" when standing in front of the bed and won't be asked about their duration.

### **Additional context**
A little thing, that might be helpful, don't know whether this would work, is, that group members, who wants to sleep in taverns, would get different rooms with beds from the waiter after purchasing so there would be no overlap.

_This might would also help to patch the survivalmode creation-club-dlc integration, where the players also need to sleep in order to be not tired anymore._

**Comment by RobbeBryssinck** [comment] 2023-01-04 19:41
Duplicate of #467

**Closed by RobbeBryssinck** 2023-01-04 19:41 UTC
Labels: Feature
