### ISSUE TITLE
Full ESL synchronization

### ISSUE THREAD

**Issue by xForcer** [tiltedphoques/TiltedEvolution#595] opened 2023-05-06 16:59 UTC
## Description

ESL loading and syncing should be fixed

Screenshot for reference
![image](https://user-images.githubusercontent.com/23403365/236637287-6f707055-4145-47ee-9645-119b3ca10874.png)

**Comment by Dragonisser** [comment] 2023-07-21 19:39
duplicate of #346 
ESL Loader is disabled.

**Closed by Dragonisser** 2023-07-21 19:39 UTC
Labels: Feature
